import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/chess-wood.jpg',
    title: 'Wood : Zero to Hero',
    rating: 5,
    ratingCount: 8,
    price: 20,
    category: 'Beginner : Free 5 Trial Classes',
  },
  {
    id: 2,
    cover: '/images/courses/chess-ivory.jpg',
    title: 'Ivory : Zero to Hero',
    rating: 5,
    ratingCount: 15,
    price: 25,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/chess-master.jpg',
    title: 'Mastering Chess Techniques Level 1',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/chess-mastery.jpg',
    title: 'Mastering Chess Techniques Level 2',
    rating: 4,
    ratingCount: 12,
    price: 40,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/chess-master.jpg',
    title: 'Mastering Chess Techniques Level 3',
    rating: 4,
    ratingCount: 32,
    price: 45,
    category: 'Advance',
  },
  {
    id: 6,
    cover: '/images/courses/chess-silver.jpg',
    title: 'Chess Champs Silver',
    rating: 5,
    ratingCount: 14,
    price: 10,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/chess-gold.jpg',
    title: 'Chess Champs Gold',
    rating: 4,
    ratingCount: 6,
    price: 15,
    category: 'Beginner',
  },
]
